spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/invest_calix?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  datasource-quartz:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/invest_calix?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    open-in-view: false

  # spring cache 설정
  cache:
    type: redis
  # redis 설정
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  # quartz 설정
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    data-source: quartz

  # Spring Boot Admin Client 설정
  boot:
    admin:
      client:
        enabled: true
        url: ${ADMIN_SERVER_URL}
        instance:
          service-base-url: ${SERVICE_BASE_URL}
          metadata:
            environment: dev
            team: "Investment Batch Team"
        username: ${ADMIN_USERNAME}
        password: ${ADMIN_PASSWORD}
        auto-registration: true
        auto-deregistration: true
        period: 10000ms

logging:
  level:
    io.github.hyeonqz: INFO
    org.springframework.batch: INFO
    org.springframework.scheduling: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,quartz,scheduledtasks
  endpoint:
    health:
      show-details: when-authorized
    quartz:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
