spring:
  datasource:
    url: jdbc:mysql://localhost:3306/invest_calix?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2

  datasource-quartz:
    url: jdbc:mysql://localhost:3306/invest_calix?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    open-in-view: false

  # spring cache 설정
  cache:
    type: redis
  # redis 설정
  data:
    redis:
      host: localhost
      port: 6379

  # quartz 설정
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    data-source: quartz

  # Spring Boot Admin Client 설정
  boot:
    admin:
      client:
        enabled: true
        url: ${ADMIN_SERVER_URL:http://localhost:9900/admin}
        instance:
          service-base-url: ${SERVICE_BASE_URL:http://localhost:9100}
          metadata:
            environment: local
            team: "Investment Batch Team"
        username: ${ADMIN_USERNAME:admin}
        password: ${ADMIN_PASSWORD:admin123!}
        auto-registration: true
        auto-deregistration: true
        period: 10000ms

logging:
  level:
    io.github.hyeonqz: INFO
    org.springframework.batch: INFO
    org.springframework.scheduling: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,quartz,scheduledtasks
  endpoint:
    health:
      show-details: when-authorized
    quartz:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
